apiVersion: v1
kind: Pod
metadata:
  name: webhook-testpod2

spec:
  containers:
  - name: nginxpod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
